"""added password column

Revision ID: 459d44b5b02d
Revises: 0e47985680fb
Create Date: 2025-09-01 17:38:52.921171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '459d44b5b02d'
down_revision = '0e47985680fb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User_data', sa.Column('password', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User_data', 'password')
    # ### end Alembic commands ###
